"""Add reporting fields

Revision ID: 0e582f750c57
Revises: 
Create Date: 2026-01-10 21:38:40.770287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e582f750c57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placement_drives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('mode', sa.String(length=50), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fathers_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('college_name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('college_name')
        batch_op.drop_column('fathers_name')

    with op.batch_alter_table('placement_drives', schema=None) as batch_op:
        batch_op.drop_column('mode')
        batch_op.drop_column('venue')

    # ### end Alembic commands ###
