"""Add Admin Profile Fields

Revision ID: 1ce1698a1634
Revises: 0e582f750c57
Create Date: 2026-01-10 22:27:54.143798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce1698a1634'
down_revision = '0e582f750c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('designation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('college_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('mobile', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_column('mobile')
        batch_op.drop_column('college_name')
        batch_op.drop_column('designation')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
